import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Subham kumar Das",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex flex-col justify-center items-center
        mx-auto p-4 max-w-2xl pt-12`}
      >
       
          <div className="w-full flex justify-center">
            <div className="shadow-md m-3 ">
              <Header />
            </div>
          </div>
          <main className="prose prose-neutral max-w-none mt-3">
            {children}
          </main>
        
      </body>
    </html>
  );
}
